### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-aha-source#1]
**Requirements**
- Integration should handle [pagination](http://www.aha.io/api#pagination) for multiple pages of results
- Integration should use [OAuth2](http://www.aha.io/api#authentication) to authenticate
- Build methods for the following: 
  - [ ] [Products](http://www.aha.io/api/resources/products#anchor-resource-products-example-get_a_list_of_all_of_the_products_in_the_account)
  - [ ] [Features](http://www.aha.io/api/resources/features#anchor-resource-features-example-get_all_features)
  - [ ] [Ideas](http://www.aha.io/api/resources/ideas#anchor-resource-ideas-example-get_all_ideas)
  - [ ] [Initiatives](http://www.aha.io/api/resources/initiatives)
  - [ ] [Product Initiatives](http://www.aha.io/api/resources/initiatives#anchor-resource-initiatives-example-get_all_initiatives_for_a_product)
  - [ ] [Product Ideas](http://www.aha.io/api/resources/ideas#anchor-resource-ideas-example-get_all_ideas_for_a_product)
  - [ ] [Product Goals](http://www.aha.io/api/resources/goals#anchor-resource-goals-example-get_all_goals_for_a_product)
  - [ ] [Release Features](http://www.aha.io/api/resources/features#anchor-resource-features-example-get_all_features_for_a_release)
  - [ ] [Product Features](http://www.aha.io/api/resources/features#anchor-resource-features-example-get_all_features_for_a_product)
  - [ ] [Product Idea Categories](http://www.aha.io/api/resources/idea_categories#anchor-resource-idea_categories-example-get_all_idea_categories_for_a_product)
  - [ ] [Product Idea Endorsements](http://www.aha.io/api/resources/idea_endorsements#anchor-resource-idea_endorsements-example-get_all_endorsements_for_an_idea)
  - [ ] [Product Competitors](http://www.aha.io/api/resources/competitors#anchor-resource-competitors-example-get_a_list_of_all_of_the_competitors_in_a_product)
  - [ ] [Product Comments](http://www.aha.io/api/resources/comments#anchor-resource-comments-example-get_all_comments_on_a_product)
  - [ ] [Feature Comments](http://www.aha.io/api/resources/comments#anchor-resource-comments-example-get_all_comments_on_a_feature)
  - [ ] [Idea Comments](http://www.aha.io/api/resources/comments#anchor-resource-comments-example-get_all_comments_on_an_idea) 
  - [ ] [Initiative Comments](http://www.aha.io/api/resources/comments#anchor-resource-comments-example-get_all_comments_on_an_initiative) 
  - [ ] [Goal Comments](http://www.aha.io/api/resources/comments#anchor-resource-comments-example-get_all_comments_on_a_goal)
  - [ ] [Idea Subscriptions](http://www.aha.io/api/resources/idea_subscriptions#anchor-resource-idea_subscriptions-example-get_all_subscriptions_for_an_idea)
  - [ ] [Account Integrations](http://www.aha.io/api/resources/integrations#anchor-resource-integrations-example-get_all_integrations_at_the_account_level)
  - [ ] [Product Integrations](http://www.aha.io/api/resources/integrations#anchor-resource-integrations-example-get_all_integrations_at_the_product_level)
  - [ ] [Product Pages](http://www.aha.io/api/resources/pages#anchor-resource-pages-example-get_all_pages_for_a_product) 
  - [ ] [Portal Users](http://www.aha.io/api/resources/portal_users#anchor-resource-portal_users-example-get_all_portal_users_for_a_product)
  - [ ] [Release Phases](http://www.aha.io/api/resources/releasephases#anchor-resource-releasephases-example-get_all_release_phases_for_a_release)
  - [ ] [Product Releases](http://www.aha.io/api/resources/releases#anchor-resource-releases-example-get_all_releases_in_a_product)
  - [ ] [Feature Tasks](http://www.aha.io/api/resources/tasks#anchor-resource-tasks-example-get_all_tasks_for_a_feature)
  - [ ] [Release Tasks](http://www.aha.io/api/resources/tasks#anchor-resource-tasks-example-get_all_tasks_for_a_release)
  - [ ] [Idea Tasks](http://www.aha.io/api/resources/tasks#anchor-resource-tasks-example-get_all_tasks_for_an_idea)
  - [ ] [Requirement Tasks](http://www.aha.io/api/resources/tasks#anchor-resource-tasks-example-get_all_tasks_for_a_requirement)
  - [ ] [Users](http://www.aha.io/api/resources/users#anchor-resource-users-example-get_all_users)
  - [ ] [Product Users](http://www.aha.io/api/resources/users#anchor-resource-users-example-get_all_users_for_a_product)

**Relevant Links**
http://www.aha.io/api

**Comment by byerc** [comment]
1-9-2017: Implementing Nock - an HTTP mocking and expectations library 

Read more here: https://davidwalsh.name/nock

**Comment by byerc** [comment]
1-10-2017: Continue to build out remaining methods and write tests for each. Clean up test.js by moving mock responses to nock-fixtures.json. Implement nock enable/disable feature so that real http requests can be made if need be.

**Comment by benjamingregory** [comment]
@byerc As you build out the methods, please put a check next to the ones that are finished in the comment above.

**Comment by byerc** [comment]
1-11-2017: All methods and tests are built and structured to Mike's liking. Today I'll be updating the readme then creating a workflow document to thorougly test the integration.

**Comment by benjamingregory** [comment]
@byerc Do you have credentials to test with?

You should talk with @beckysteele and @sammf on what info they would like to get out of Aha since they use it the most.

**Comment by byerc** [comment]
@benjamingregory you gave me your credentials last week so I have an access token, but I don't know if it would be better to use someone else's account. I will speak with them, that'll be really helpful. Thanks!

**Comment by benjamingregory** [comment]
You're fine to use those then. Just couldn't remember if I gave them to you

**Comment by benjamingregory** [comment]
@byerc Also talk with @gregbrunk - he's a big Aha user.

**Comment by byerc** [comment]
1-12-2017: Integration is running in Airflow. Now I'll work to take pagination into account. @beckysteele is also working to provide me with details on how Aha is being used and the specific endpoints that will benefit us internally.

**Comment by byerc** [comment]
1-13-2017: Implemented pagination handling. I need to update all tests to reflect that.  I am now encountering weird issues only when running in Airflow. Mike and I are meeting this morning to debug. Following that, I'll be reviewing documentation Becky gave me.

**Comment by byerc** [comment]
1-17-2017: Resolved the issue, or what was thought to be an issue, with the integration. I was asked by Mike and Alois to help with analytics-ios for some time on Friday. Today I'll finish updating all tests in Aha

**Comment by byerc** [comment]
1-23-2017: Will fix issues with pull request
